admin:
    name: admin
    password: admin
interval:
    feed: 3
    fetch: 2
    websocket: 5
message: null
source:
    id: -1
    name: accepted-laps
site:
    show_live: True
    freeze: null
telraam:
    api: https://telraam.velteq.com # http://host.docker.internal:8080
    ws: ws://host.docker.internal:8765
