admin:
  name: admin
  password: admin
api_token: lekey
interval:
  feed: 10
  fetch: 2
  websocket: 5
lap_source:
  id: 8
  name: robust-lapper
position_source:
  id: 6
  name: nostradamus
site:
  freeze: null
  message: null
telraam:
  api: http://host.docker.internal:8080
  ws: ws://host.docker.internal:8080/ws
