admin:
  name: admin
  password: admin
api_token: lekey
interval:
  feed: 10
  fetch: 2
  websocket: 5
lap_source:
  id: 5
  name: robust-lapper
position_source:
  id: 1
  name: nostradamus
site:
  freeze: null
  message: null
telraam:
  api: http://localhost:8080
  ws: ws://localhost:8080/ws
