admin:
  name: admin
  password: admin
interval:
  feed: 10
  fetch: 2
  websocket: 5
site:
  freeze: 3600000
  message: Je Mama
  show_live: true
source:
  id: -1
  name: accepted-laps
telraam:
  api: http://localhost:8080
  ws: ws://localhost:8080/ws
