admin:
  name: admin
  password: admin
interval:
  feed: 3
  fetch: 2
  websocket: 5
message: Je Mama
site:
  freeze: null
  show_live: true
source:
  id: -1
  name: accepted-laps
telraam:
  api: http://localhost:8080
  ws: ws://localhost:8080
