admin:
  name: admin
  password: admin
api_token: lekey
interval:
  feed: 10
  fetch: 2
  websocket: 5
site:
  freeze: null
  message: test-message
source:
  id: -1
  name: accepted-laps
telraam:
  api: http://localhost:8080
  ws: ws://localhost:8080/ws
