version: '3'

services:
    loxsi:
        build:
            context: .
        container_name: loxsi
        ports:
          - "8080:80"
        volumes:
          - type: bind
            source: ./config.yml
            target: /loxsi/config.yml
