version: "3.9"

services:
  loxsi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: loxsi
    ports:
      - "8080:80"
    volumes:
      - "./:/loxsi/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # command: "uvicorn --host 0.0.0.0 --port 80 main:app --reload"
