version: "3.9"

services:
  loxsi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loxsi
    ports:
      - "8000:80"
    volumes:
      - "./:/loxsi/"
    command: "uvicorn --host 0.0.0.0 --port 80 main:app --reload"
